// src/config/prompts/resources.js
// 이벤트 스크립트에서 사용할 수 있는 bg / music / sound / expression 파일명과 캐릭터별 emotion 목록.
// 프론트 constants/eventAssets.ts 의 키와 반드시 일치해야 한다.

const resources = {
  공통: {
    bg: [
      'BG_AbydosCouncilRoom.jpg',
      'BG_AbydosResidence.jpg',
      'BG_AbydosRuinArea.jpg',
      'BG_AbydosTrainStation.jpg',
      'BG_AbandonedCorridor_Night.jpg',
      'BG_AbandonedWarehouse.jpg',
      'BG_Amusement.jpg',
      'BG_Arcade.jpg',
      'BG_AronaRoom.jpg',
      'BG_Atelier.jpg',
      'BG_Auditorium.jpg',
      'BG_BambooForest.jpg',
      'BG_Bank.jpg',
      'BG_BeachFestival.jpg',
      'BG_BeachFrontSide.jpg',
      'BG_BeachShopInSide.jpg',
      'BG_Beachside.jpg',
      'BG_BeachsideShop.jpg',
      'BG_BeachStage.jpg',
      'BG_BigBridge.jpg',
      'BG_BigPlaza.jpg',
      'BG_BlackMarket.jpg',
      'BG_BuildingRooftop.jpg',
      'BG_BusInside.jpg',
      'BG_BusStation.jpg',
      'BG_CampInside.jpg',
      'BG_Campus.jpg',
      'BG_CampSite.jpg',
      'BG_CommitteeRoom.jpg',
      'BG_Convenience.jpg',
      'BG_BuildingBackStreet.jpg',
      'BG_BuildingCorridor.jpg',
      'BG_Broadcastingroom.jpg',
      'BG_CherinoOffice.jpg',
      'BG_CityOffice.jpg',
      'BG_CitySqaure.jpg',
      'BG_CityTown.jpg',
      'BG_ClassCorridor.jpg',
      'BG_ClassStairs.jpg',
      'BG_ComputerCenter.jpg',
      'BG_ConstructionSite.jpg',
      'BG_ConventionHall.jpg',
      'BG_CraftChamber.jpg',
      'BG_CruiseRooftop.jpg',
      'BG_DecagrammatonFront.jpg',
      'BG_DecagrammatonLabortory.jpg',
      'BG_DemolitionCity.jpg',
      'BG_DesertCamp.jpg',
      'BG_DessertCafe.jpg',
      'BG_DesertRailWay.jpg',
      'BG_Dormitory.jpg',
      'BG_DownTown.jpg',
      'BG_DrawingRoom.jpg',
      'BG_Elevator.jpg',
      'BG_Empty_KivotosStadium.jpg',
      'BG_EmptySwimmingPool.jpg',
      'BG_EriduCityTown.jpg',
      'BG_ExhibitionHall.jpg',
      'BG_FamilyRestaurant.jpg',
      'BG_FastfoodRestaurant.jpg',
      'BG_FineDining.jpg',
      'BG_FireplaceDormitory.jpg',
      'BG_FishingVillage.jpg',
      'BG_FoodCartRamen.jpg',
      'BG_ForestRailRoad.jpg',
      'BG_ForestRoad2.jpg',
      'BG_GameDevRoom.jpg',
      'BG_GehennaCampus.jpg',
      'BG_GehennaClassRoom.jpg',
      'BG_GehennaClubRoom_Night.jpg',
      'BG_GehennaCorridor_Party.jpg',
      'BG_GehennaCouncilHall.jpg',
      'BG_GehennaPartyRoom.jpg',
      'BG_GehennaStreet.jpg',
      'BG_GehennaStudentCouncil_Tent.jpg',
      'BG_SCHALE.jpg',
      'BG_SCHALE2.jpg',
    ],

    music: [
      'aira.mp3',
      'crossfire.mp3',
      'formless_dream.mp3',
      'funky_road.mp3',
      'future_bossa.mp3',
      'honey_jam.mp3',
      'koi_is_love.mp3',
      'lovely_picnic.mp3',
      'luminous_memory.mp3',
      'mechanical_jungle.mp3',
      'midnight_trip.mp3',
      'midsummer_cat.mp3',
      'mischievous_step.mp3',
      'morose_dreamer.mp3',
      'shady_girls.mp3',
      'unwelcome_school.mp3',
      'walkthrough.mp3',
    ],
    sound: [
      'SE_49mm_01.mp3',
      'SE_Appear_01a.mp3',
      'SE_Answer_01.mp3',
      'SE_BoomEffect_02.mp3',
      'SE_Drill_02.mp3',
      'SE_DoorSlowOpen_01.mp3',
      'SE_DoorClose_01.mp3',
      'SE_DoorBell_01.mp3',
      'SE_Dog_01a.mp3',
      'SE_Denied_01.mp3',
      'SE_Cup_02.mp3',
      'SE_Crowd_05.mp3',
      'SE_Crowd_02.mp3',
      'SE_Cricket_01.mp3',
      'SE_Cook_03.mp3',
      'SE_Confirm_02.mp3',
      'SE_Confirm_01.mp3',
      'SE_ClockAlarm_01.mp3',
      'SE_Clock_02.mp3',
      'SE_Clap_01.mp3',
      'SE_Cat_01.mp3',
      'SE_Cartoon_02.mp3',
      'SE_Cartoon_01.mp3',
      'SE_CarHorn_01.mp3',
      'SE_BushRusting_02b.mp3',
      'SE_Burning_02.mp3',
      'SE_Bug_01.mp3',
      'SE_BoxShake_02.mp3',
      'SE_BoomFuse_02a.mp3',
      'SE_Boom_01.mp3',
      'SE_Book_02.mp3',
      'SE_Bird_01.mp3',
      'SE_BikeBell_01.mp3',
      'SE_BeepScreen_01.mp3',
      'SE_Beep_01.mp3',
      'SE_Bear_01.mp3',
      'SE_Army_01.mp3',
      'SE_Alarm_02.mp3',
    ],
    expression: [
      'Headpat.png',
      'question_mark.png',
      'Question2.png',
      'sweat.png',
    ],
  },

  호시노: {
    emotions: [
      'hoshino_angry.png',
      'hoshino_bigLaugh.png',
      'hoshino_dontknowAnything.png',
      'hoshino_feelGood.png',
      'hoshino_makebigEye.png',
      'hoshino_serious.png',
      'hoshino_strongSurprised.png',
      'hoshino_surprised.png',
      'hoshino_suspicious.png',
      'hoshino_weakLaugh.png',
      'hoshino_yawn.png',
      'hoshino_yawn2.png',
      'hoshino_swimsuit_angry.png',
      'hoshino_swimsuit_bewildered.png',
      'hoshino_swimsuit_bigsmile.png',
      'hoshino_swimsuit_bigyawn.png',
      'hoshino_swimsuit_confused.png',
      'hoshino_swimsuit_consider.png',
      'hoshino_swimsuit_consider2.png',
      'hoshino_swimsuit_embarrassed.png',
      'hoshino_swimsuit_feeling.png',
      'hoshino_swimsuit_helpless_but_cute.png',
      'hoshino_swimsuit_helpless_but_cute2.png',
      'hoshino_swimsuit_serious.png',
      'hoshino_swimsuit_smile.png',
      'hoshino_swimsuit_smile2.png',
      'hoshino_swimsuit_smile3.png',
      'hoshino_swimsuit_sunglass.png',
      'hoshino_swimsuit_surprised.png',
      'hoshino_swimsuit_upset.png',
      'hoshino_swimsuit_yawn.png',
    ],
  },

  히나: {
    emotions: [
      'hina_angry.png',
      'hina_bigsmile.png',
      'hina_closingeyes.png',
      'hina_embarrassed.png',
      'hina_embarrassed2.png',
      'hina_embarrassed3.png',
      'hina_expressionless.png',
      'hina_littlebitembarrassed.png',
      'hina_makebigeyes.png',
      'hina_serious.png',
      'hina_shout.png',
      'hina_smilewithteeth.png',
      'hina_sweating.png',
      'hina_takenaback.png',
      'hina_upset.png',
      'hina_weaksmile.png',
      'hina_weaksmile2.png',
      'hina_wink.png',
      'hina_swimsuit_angry.png',
      'hina_swimsuit_angry2.png',
      'hina_swimsuit_bigsmile.png',
      'hina_swimsuit_default.png',
      'hina_swimsuit_embarrassed.png',
      'hina_swimsuit_nervous.png',
      'hina_swimsuit_strugglle.png',
      'hina_swimsuit_thinking.png',
      'hina_swimsuit_weaksmile.png',
      'hina_swimsuit_wink.png',
    ],
  },

  게헨나학생: {
    emotions: [
      'gehenna_student_default.png',
      'gehenna_student_shout.png',
      'gehenna_student_gnash_teeth.png',
      'gehenna_student_smile.png',
      'gehenna_student_speaking.png',
    ],
  },

  로봇: {
    emotions: [
      'robot_default.png',
      'robot_serious.png',
      'robot_lethargic.png',
      'robot_grimace.png',
      'robot_fainted.png',
      'robot_crying.png',
      'robot_angry.png',
      'robot_confused.png',
      'robot_smile.png',
    ],
  },

  시민동물: {
    emotions: [
      'citizen_animal_dog.png 주로 학생 역할임',
      'citizen_animal_dog2.png 주로 장사하는 역할임',
      'citizen_animal_dog3.png 주로 일반 시민 역할임',
      'citizen_animal_dog4.png 주로 일반 시민 역할임2',
      'citizen_animal_cat.png 주로 일반 시민 역할임3',
      'citizen_animal_bandaged_dog.png',
      'citizen_animal_engineer_dog.png 정비 쪽 일하는 역할임',
    ],
  },

  노노미: {
    emotions: [
      'nonomi_default.png',
      'nonomi_smile.png',
      'nonomi_speaking.png',
      'nonomi_confuse.png',
      'nonomi_little_bit_angry.png',
      'nonomi_angry_with_shout.png',
      'nonomi_satisfaction.png',
      'nonomi_closing_eye.png',
      'nonomi_weak_smile.png',
      'nonomi_upset.png',
      'nonomi_upset2.png',
      'nonomi_worry.png',
      'nonomi_worry2.png',
      'nonomi_awkward.png',
      'nonomi_blank_stare.png',
      'nonomi_sly_smile.png',
      'nonomi_sly_smile2.png',
      'nonomi_shock.png',
      'nonomi_little_bit_sad.png',
      'nonomi_smile_with_closing_eyes.png',
    ],
  },

  이부키: {
    emotions: [
      'ibuki_default.png',
      'ibuki_weaksmile.png',
      'ibuki_curious.png',
      'ibuki_bigsmile.png',
      'ibuki_confused.png',
      'ibuki_angry.png',
      'ibuki_crying.png',
      'ibuki_interesting.png',
      'ibuki_notfunny.png',
      'ibuki_exciting.png',
      'ibuki_sulky_face.png',
      'ibuki_sad.png',
      'ibuki_sad_and_crying.png',
      'ibuki_deadpan.png',
      'ibuki_cold_stare.png',
      'ibuki_confidence.png',
      'ibuki_sleepy.png',
      'ibuki_hurt.png',
      'ibuki_smile_with_closing_eyes.png',
    ],
  },

  시로코: {
    emotions: [
      'shiroko_default.png',
      'shiroko_angry.png',
      'shiroko_angry_and_shout.png',
      'shiroko_cold_stare.png',
      'shiroko_cold_stare_open_mouth.png',
      'shiroko_cold_stare_open_mouth2.png',
      'shiroko_confuse.png',
      'shiroko_confuse2.png',
      'shiroko_crying.png',
      'shiroko_endure.png',
      'shiroko_open_mouth.png',
      'shiroko_painful.png',
      'shiroko_weak_smile.png',
      'shiroko_worry.png',
      'shiroko_worry2.png',
    ],
  },

  세리카: {
    emotions: [
      'serika_default.png',
      'serika_angry.png',
      'serika_bigangry.png',
      'serika_bigsmile.png',
      'serika_closingeyes.png',
      'serika_cold_stare.png',
      'serika_confused.png',
      'serika_embarrassed.png',
      'serika_little_bit_angry.png',
      'serika_serious.png',
      'serika_speaking.png',
      'serika_upset.png',
      'serika_weaksmile.png',
      'serika_worry.png',
    ],
  },


  아리스: {
    emotions: [
      'aris_angry.png',
      'aris_awkward.png',
      'aris_bigsmile.png',
      'aris_brave.png',
      'aris_difficult.png',
      'aris_disgusting.png',
      'aris_expressionless.png',
      'aris_expressionless2.png',
      'aris_impressive.png',
      'aris_smile.png',
      'aris_smile_with_tear.png',
      'aris_smile_with_tear2.png',
      'aris_smile2.png',
      'aris_tear.png',
      'aris_trouble.png',
      'aris_very_angry.png',
      'aris_very_angry2.png',
      'aris_closing_eyes.png',
    ],
  },
  
  아코: {
    emotions: [
      'ako_angry.png',
      'ako_awkward.png',
      'ako_bigsmile.png',
      'ako_crying.png',
      'ako_curious.png',
      'ako_eyesmile.png',
      'ako_mental_out.png',
      'ako_serious.png',
      'ako_shout.png',
      'ako_shout_with_angry.png',
      'ako_smile.png',
      'ako_smile_with_closing_eyes.png',
      'ako_sweating.png',
      'ako_upset.png',
      'ako_veryangry1.png',
      'ako_veryangry2.png',
      'ako_weaksmile.png',
    ],
  },

  발키리학생: {
    emotions: [
      'valkyrie_student_default.png',
      'valkyrie_student_speaking.png',
      'valkyrie_student_smile.png',
      'valkyrie_student_awkward.png',
      'valkyrie_student_serious.png',
      'valkyrie_student_uncomfortable.png',
      'valkyrie_student_terrified.png',
      'valkyrie_student_speechless.png',
    ],
  },

  적: {
    emotions: [
      'sukeban_thug_smg_default.png',
      'sukeban_thug_smg_angry.png',
      'sukeban_thug_smg_uncomfortable.png',
      'sukeban_thug_smg_terrified.png',
      'sukeban_thug_hmg_default.png',
      'sukeban_thug_hmg_angry.png',
      'sukeban_thug_hmg_uncomfortable.png',
      'sukeban_thug_hmg_terrified.png',
      'small_amas.png',
      'saint_justina_member_ghost.png',
      'saint_justina_member_ghost_swimsuit.png',
      'kaiser_pmc_enemy1.png',
      'kaiser_pmc_enemy2.png',
      'kaiser_pmc_director.png',
      'kaiser_pmc_general.png',
    ],
  },

  츠루기: {
    emotions: [
      'tsurugi_awkward.png',
      'tsurugi_confused.png',
      'tsurugi_curious.png',
      'tsurugi_default.png',
      'tsurugi_embarrassed.png',
      'tsurugi_embarrassed2.png',
      'tsurugi_happy.png',
      'tsurugi_normal.png',
      'tsurugi_serious.png',
      'tsurugi_shock.png',
      'tsurugi_smile.png',
      'tsurugi_smile2.png',
      'tsurugi_space_out.png',
      'tsurugi_dark_smile.png',
    ],
  },

  트리니티정의실현부: {
    emotions: [
      'justice_task_force_member_default.png',
      'justice_task_force_member_speaking.png',
      'justice_task_force_member_serious.png',
      'justice_task_force_member_awkward.png',
      'justice_task_force_member_uncomfortable.png',
    ],
  },

  게헨나선도부: {
    emotions: [
      'prefect_team_member_default.png',
      'prefect_team_member_speaking.png',
      'prefect_team_member_smile.png',
      'prefect_team_member_awkward.png',
      'prefect_team_member_uncomfortable.png',
      'prefect_team_member_embarrassed.png',
      'prefect_team_member_serious.png',
    ],
  },

  백귀야행학생: {
    emotions: [
      'hyakkiyako_student_default.png',
      'hyakkiyako_student_speaking.png',
      'hyakkiyako_student_confused.png',
      'hyakkiyako_student_serious.png',
      'hyakkiyako_student_awkward.png',
    ],
  },

  현룡문학생: {
    emotions: [
      'genryumon_student_default.png',
      'genryumon_student_speaking.png',
      'genryumon_student_smile.png',
      'genryumon_student_uncomfortable.png',
      'genryumon_student_shout.png',
      'genryumon_student_sad.png',
      'genryumon_student_angry.png',
      'genryumon_student_serious.png',
    ],
  },

  코하루: {
    emotions: [
      'koharu_default.png',
      'koharu_default2.png',
      'koharu_bigsmile.png',
      'koharu_closingeyes.png',
      'koharu_crying.png',
      'koharu_disgusting.png',
      'koharu_embarrassed.png',
      'koharu_embarrassed2.png',
      'koharu_interesting.png',
      'koharu_say_hentai.png',
      'koharu_shout.png',
      'koharu_shout2.png',
      'koharu_suspicious.png',
    ],
  },

  유우카: {
    emotions: [
      'yuuka_awkward.png',
      'yuuka_bigsmile.png',
      'yuuka_closing_eyes.png',
      'yuuka_default.png',
      'yuuka_embarrassed.png',
      'yuuka_scheming.png',
      'yuuka_speaking.png',
      'yuuka_suspicious.png',
    ],
  },
  
};

module.exports = { resources };
