/* 배경 */
export const bgMap: Record<string, any> = {
  BG_AbydosCouncilRoom: require('../../assets/images/background/BG_AbydosCouncilRoom.jpg'),
  BG_AbydosResidence: require('../../assets/images/background/BG_AbydosResidence.jpg'),
  BG_AbydosRuinArea: require('../../assets/images/background/BG_AbydosRuinArea.jpg'),
  BG_AbydosTrainStation: require('../../assets/images/background/BG_AbydosTrainStation.jpg'),
  BG_AbandonedCorridor_Night: require('../../assets/images/background/BG_AbandonedCorridor_Night.jpg'),
  BG_AbandonedWarehouse: require('../../assets/images/background/BG_AbandonedWarehouse.jpg'),
  BG_Amusement: require('../../assets/images/background/BG_Amusement.jpg'),
  BG_Arcade: require('../../assets/images/background/BG_Arcade.jpg'),
  BG_AronaRoom: require('../../assets/images/background/BG_AronaRoom.jpg'),
  BG_Atelier: require('../../assets/images/background/BG_Atelier.jpg'),
  BG_Auditorium: require('../../assets/images/background/BG_Auditorium.jpg'),
  BG_BambooForest: require('../../assets/images/background/BG_BambooForest.jpg'),
  BG_Bank: require('../../assets/images/background/BG_Bank.jpg'),
  BG_BeachFestival: require('../../assets/images/background/BG_BeachFestival.jpg'),
  BG_BeachFrontSide: require('../../assets/images/background/BG_BeachFrontSide.jpg'),
  BG_BeachShopInSide: require('../../assets/images/background/BG_BeachShopInSide.jpg'),
  BG_Beachside: require('../../assets/images/background/BG_Beachside.jpg'),
  BG_BeachsideShop: require('../../assets/images/background/BG_BeachsideShop.jpg'),
  BG_BeachStage: require('../../assets/images/background/BG_BeachStage.jpg'),
  BG_BigBridge: require('../../assets/images/background/BG_BigBridge.jpg'),
  BG_BigPlaza: require('../../assets/images/background/BG_BigPlaza.jpg'),
  BG_BlackMarket: require('../../assets/images/background/BG_BlackMarket.jpg'),
  BG_BuildingRooftop: require('../../assets/images/background/BG_BuildingRooftop.jpg'),
  BG_BusInside: require('../../assets/images/background/BG_BusInside.jpg'),
  BG_BusStation: require('../../assets/images/background/BG_BusStation.jpg'),
  BG_CampInside: require('../../assets/images/background/BG_CampInside.jpg'),
  BG_Campus: require('../../assets/images/background/BG_Campus.jpg'),
  BG_CampSite: require('../../assets/images/background/BG_CampSite.jpg'),
  BG_CommitteeRoom: require('../../assets/images/background/BG_CommitteeRoom.jpg'),
  BG_Convenience: require('../../assets/images/background/BG_Convenience.jpg'),
  BG_BuildingBackStreet: require('../../assets/images/background/BG_BuildingBackStreet.jpg'),
  BG_BuildingCorridor: require('../../assets/images/background/BG_BuildingCorridor.jpg'),
  BG_Broadcastingroom: require('../../assets/images/background/BG_Broadcastingroom.jpg'),
  BG_CherinoOffice: require('../../assets/images/background/BG_CherinoOffice.jpg'),
  BG_CityOffice: require('../../assets/images/background/BG_CityOffice.jpg'),
  BG_CitySqaure: require('../../assets/images/background/BG_CitySqaure.jpg'),
  BG_CityTown: require('../../assets/images/background/BG_CityTown.jpg'),
  BG_ClassCorridor: require('../../assets/images/background/BG_ClassCorridor.jpg'),
  BG_ClassStairs: require('../../assets/images/background/BG_ClassStairs.jpg'),
  BG_ComputerCenter: require('../../assets/images/background/BG_ComputerCenter.jpg'),
  BG_ConstructionSite: require('../../assets/images/background/BG_ConstructionSite.jpg'),
  BG_ConventionHall: require('../../assets/images/background/BG_ConventionHall.jpg'),
  BG_CraftChamber: require('../../assets/images/background/BG_CraftChamber.jpg'),
  BG_CruiseRooftop: require('../../assets/images/background/BG_CruiseRooftop.jpg'),
  BG_DecagrammatonFront: require('../../assets/images/background/BG_DecagrammatonFront.jpg'),
  BG_DecagrammatonLabortory: require('../../assets/images/background/BG_DecagrammatonLabortory.jpg'),
  BG_DemolitionCity: require('../../assets/images/background/BG_DemolitionCity.jpg'),
  BG_DesertCamp: require('../../assets/images/background/BG_DesertCamp.jpg'),
  BG_DessertCafe: require('../../assets/images/background/BG_DessertCafe.jpg'),
  BG_DesertRailWay: require('../../assets/images/background/BG_DesertRailWay.jpg'),
  BG_Dormitory: require('../../assets/images/background/BG_Dormitory.jpg'),
  BG_DownTown: require('../../assets/images/background/BG_DownTown.jpg'),
  BG_DrawingRoom: require('../../assets/images/background/BG_DrawingRoom.jpg'),
  BG_Elevator: require('../../assets/images/background/BG_Elevator.jpg'),
  BG_Empty_KivotosStadium: require('../../assets/images/background/BG_Empty_KivotosStadium.jpg'),
  BG_EmptySwimmingPool: require('../../assets/images/background/BG_EmptySwimmingPool.jpg'),
  BG_EriduCityTown: require('../../assets/images/background/BG_EriduCityTown.jpg'),
  BG_ExhibitionHall: require('../../assets/images/background/BG_ExhibitionHall.jpg'),
  BG_FamilyRestaurant: require('../../assets/images/background/BG_FamilyRestaurant.jpg'),
  BG_FastfoodRestaurant: require('../../assets/images/background/BG_FastfoodRestaurant.jpg'),
  BG_FineDining: require('../../assets/images/background/BG_FineDining.jpg'),
  BG_FireplaceDormitory: require('../../assets/images/background/BG_FireplaceDormitory.jpg'),
  BG_FishingVillage: require('../../assets/images/background/BG_FishingVillage.jpg'),
  BG_FoodCartRamen: require('../../assets/images/background/BG_FoodCartRamen.jpg'),
  BG_ForestRailRoad: require('../../assets/images/background/BG_ForestRailRoad.jpg'),
  BG_ForestRoad2: require('../../assets/images/background/BG_ForestRoad2.jpg'),
  BG_GameDevRoom: require('../../assets/images/background/BG_GameDevRoom.jpg'),
  BG_GehennaCampus: require('../../assets/images/background/BG_GehennaCampus.jpg'),
  BG_GehennaClassRoom: require('../../assets/images/background/BG_GehennaClassRoom.jpg'),
  BG_GehennaClubRoom_Night: require('../../assets/images/background/BG_GehennaClubRoom_Night.jpg'),
  BG_GehennaCorridor_Party: require('../../assets/images/background/BG_GehennaCorridor_Party.jpg'),
  BG_GehennaCouncilHall: require('../../assets/images/background/BG_GehennaCouncilHall.jpg'),
  BG_GehennaPartyRoom: require('../../assets/images/background/BG_GehennaPartyRoom.jpg'),
  BG_GehennaStreet: require('../../assets/images/background/BG_GehennaStreet.jpg'),
  BG_GehennaStudentCouncil_Tent: require('../../assets/images/background/BG_GehennaStudentCouncil_Tent.jpg'),
  BG_SCHALE: require('../../assets/images/background/BG_SCHALE.jpg'),
  BG_SCHALE2: require('../../assets/images/background/BG_SCHALE2.jpg'),
} as const;

/* 표정 */
export const emotionMap: Record<string, any> = {
  // 호시노 기본
  hoshino_angry: require('../../assets/images/hoshino/hoshino_angry.png'),
  hoshino_bigLaugh: require('../../assets/images/hoshino/hoshino_bigLaugh.png'),
  hoshino_dontknowAnything: require('../../assets/images/hoshino/hoshino_dontknowAnything.png'),
  hoshino_feelGood: require('../../assets/images/hoshino/hoshino_feelGood.png'),
  hoshino_makebigEye: require('../../assets/images/hoshino/hoshino_makebigEye.png'),
  hoshino_serious: require('../../assets/images/hoshino/hoshino_serious.png'),
  hoshino_strongSurprised: require('../../assets/images/hoshino/hoshino_strongSurprised.png'),
  hoshino_surprised: require('../../assets/images/hoshino/hoshino_surprised.png'),
  hoshino_suspicious: require('../../assets/images/hoshino/hoshino_suspicious.png'),
  hoshino_weakLaugh: require('../../assets/images/hoshino/hoshino_weakLaugh.png'),
  hoshino_yawn: require('../../assets/images/hoshino/hoshino_yawn.png'),
  hoshino_yawn2: require('../../assets/images/hoshino/hoshino_yawn2.png'),

  // 호시노 수영복
  hoshino_swimsuit_angry: require('../../assets/images/hoshino/hoshino_swimsuit_angry.png'),
  hoshino_swimsuit_bewildered: require('../../assets/images/hoshino/hoshino_swimsuit_bewildered.png'),
  hoshino_swimsuit_bigsmile: require('../../assets/images/hoshino/hoshino_swimsuit_bigsmile.png'),
  hoshino_swimsuit_bigyawn: require('../../assets/images/hoshino/hoshino_swimsuit_bigyawn.png'),
  hoshino_swimsuit_confused: require('../../assets/images/hoshino/hoshino_swimsuit_confused.png'),
  hoshino_swimsuit_consider: require('../../assets/images/hoshino/hoshino_swimsuit_consider.png'),
  hoshino_swimsuit_consider2: require('../../assets/images/hoshino/hoshino_swimsuit_consider2.png'),
  hoshino_swimsuit_embarrassed: require('../../assets/images/hoshino/hoshino_swimsuit_embarrassed.png'),
  hoshino_swimsuit_feeling: require('../../assets/images/hoshino/hoshino_swimsuit_feeling.png'),
  hoshino_swimsuit_helpless_but_cute: require('../../assets/images/hoshino/hoshino_swimsuit_helpless_but_cute.png'),
  hoshino_swimsuit_helpless_but_cute2: require('../../assets/images/hoshino/hoshino_swimsuit_helpless_but_cute2.png'),
  hoshino_swimsuit_serious: require('../../assets/images/hoshino/hoshino_swimsuit_serious.png'),
  hoshino_swimsuit_smile: require('../../assets/images/hoshino/hoshino_swimsuit_smile.png'),
  hoshino_swimsuit_smile2: require('../../assets/images/hoshino/hoshino_swimsuit_smile2.png'),
  hoshino_swimsuit_smile3: require('../../assets/images/hoshino/hoshino_swimsuit_smile3.png'),
  hoshino_swimsuit_sunglass: require('../../assets/images/hoshino/hoshino_swimsuit_sunglass.png'),
  hoshino_swimsuit_surprised: require('../../assets/images/hoshino/hoshino_swimsuit_surprised.png'),
  hoshino_swimsuit_upset: require('../../assets/images/hoshino/hoshino_swimsuit_upset.png'),
  hoshino_swimsuit_yawn: require('../../assets/images/hoshino/hoshino_swimsuit_yawn.png'),

  // 히나 기본
  hina_angry: require('../../assets/images/hina/hina_angry.png'),
  hina_bigsmile: require('../../assets/images/hina/hina_bigsmile.png'),
  hina_closingeyes: require('../../assets/images/hina/hina_closingeyes.png'),
  hina_embarrassed: require('../../assets/images/hina/hina_embarrassed.png'),
  hina_embarrassed2: require('../../assets/images/hina/hina_embarrassed2.png'),
  hina_embarrassed3: require('../../assets/images/hina/hina_embarrassed3.png'),
  hina_expressionless: require('../../assets/images/hina/hina_expressionless.png'),
  hina_littlebitembarrassed: require('../../assets/images/hina/hina_littlebitembarrassed.png'),
  hina_makebigeyes: require('../../assets/images/hina/hina_makebigeyes.png'),
  hina_serious: require('../../assets/images/hina/hina_serious.png'),
  hina_shout: require('../../assets/images/hina/hina_shout.png'),
  hina_smilewithteeth: require('../../assets/images/hina/hina_smilewithteeth.png'),
  hina_sweating: require('../../assets/images/hina/hina_sweating.png'),
  hina_takenaback: require('../../assets/images/hina/hina_takenaback.png'),
  hina_upset: require('../../assets/images/hina/hina_upset.png'),
  hina_weaksmile: require('../../assets/images/hina/hina_weaksmile.png'),
  hina_weaksmile2: require('../../assets/images/hina/hina_weaksmile2.png'),
  hina_wink: require('../../assets/images/hina/hina_wink.png'),

  // 히나 수영복
  hina_swimsuit_angry: require('../../assets/images/hina/hina_swimsuit_angry.png'),
  hina_swimsuit_angry2: require('../../assets/images/hina/hina_swimsuit_angry2.png'),
  hina_swimsuit_bigsmile: require('../../assets/images/hina/hina_swimsuit_bigsmile.png'),
  hina_swimsuit_default: require('../../assets/images/hina/hina_swimsuit_default.png'),
  hina_swimsuit_embarrassed: require('../../assets/images/hina/hina_swimsuit_embarrassed.png'),
  hina_swimsuit_nervous: require('../../assets/images/hina/hina_swimsuit_nervous.png'),
  hina_swimsuit_strugglle: require('../../assets/images/hina/hina_swimsuit_strugglle.png'),
  hina_swimsuit_thinking: require('../../assets/images/hina/hina_swimsuit_thinking.png'),
  hina_swimsuit_weaksmile: require('../../assets/images/hina/hina_swimsuit_weaksmile.png'),
  hina_swimsuit_wink: require('../../assets/images/hina/hina_swimsuit_wink.png'),

  // 게헨나 학생
  gehenna_student_default: require('../../assets/images/gehenna_student/gehenna_student_default.png'),
  gehenna_student_shout: require('../../assets/images/gehenna_student/gehenna_student_shout.png'),
  gehenna_student_gnash_teeth: require('../../assets/images/gehenna_student/gehenna_student_gnash_teeth.png'),
  gehenna_student_smile: require('../../assets/images/gehenna_student/gehenna_student_smile.png'),
  gehenna_student_speaking: require('../../assets/images/gehenna_student/gehenna_student_speaking.png'),

  // 로봇
  robot_default: require('../../assets/images/robot/robot_default.png'),
  robot_serious: require('../../assets/images/robot/robot_serious.png'),
  robot_lethargic: require('../../assets/images/robot/robot_lethargic.png'),
  robot_grimace: require('../../assets/images/robot/robot_grimace.png'),
  robot_fainted: require('../../assets/images/robot/robot_fainted.png'),
  robot_crying: require('../../assets/images/robot/robot_crying.png'),
  robot_angry: require('../../assets/images/robot/robot_angry.png'),
  robot_confused: require('../../assets/images/robot/robot_confused.png'),
  robot_smile: require('../../assets/images/robot/robot_smile.png'),

  // 시민/동물
  citizen_animal_dog: require('../../assets/images/citizen/Citizen_Animal_Dog.png'),
  citizen_animal_dog2: require('../../assets/images/citizen/Citizen_Animal_Dog2.png'),
  citizen_animal_dog3: require('../../assets/images/citizen/Citizen_Animal_Dog3.png'),
  citizen_animal_dog4: require('../../assets/images/citizen/Citizen_Animal_Dog4.png'),
  citizen_animal_cat: require('../../assets/images/citizen/Citizen_Animal_Cat.png'),
  citizen_animal_bandaged_dog: require('../../assets/images/citizen/Citizen_Animal_Bandaged_Dog.png'),
  citizen_animal_engineer_dog: require('../../assets/images/citizen/Citizen_Animal_Engineer_Dog.png'),
} as const;

/* BGM */
export const musicMap: Record<string, any> = {
  'aira.mp3': require('../../assets/music/aira.mp3'),
  'crossfire.mp3': require('../../assets/music/crossfire.mp3'),
  'formless_dream.mp3': require('../../assets/music/formless_dream.mp3'),
  'funky_road.mp3': require('../../assets/music/funky_road.mp3'),
  'future_bossa.mp3': require('../../assets/music/future_bossa.mp3'),
  'honey_jam.mp3': require('../../assets/music/honey_jam.mp3'),
  'koi_is_love.mp3': require('../../assets/music/koi_is_love.mp3'),
  'lovely_picnic.mp3': require('../../assets/music/lovely_picnic.mp3'),
  'luminous_memory.mp3': require('../../assets/music/luminous_memory.mp3'),
  'mechanical_jungle.mp3': require('../../assets/music/mechanical_jungle.mp3'),
  'midnight_trip.mp3': require('../../assets/music/midnight_trip.mp3'),
  'midsummer_cat.mp3': require('../../assets/music/midsummer_cat.mp3'),
  'mischievous_step.mp3': require('../../assets/music/mischievous_step.mp3'),
  'morose_dreamer.mp3': require('../../assets/music/morose_dreamer.mp3'),
  'shady_girls.mp3': require('../../assets/music/shady_girls.mp3'),
  'unwelcome_school.mp3': require('../../assets/music/unwelcome_school.mp3'),
  'walkthrough.mp3': require('../../assets/music/walkthrough.mp3'),
} as const;

/* SFX */
export const sfxMap : Record<string, any> = {
  'SE_49mm_01.mp3': require('../../assets/sound/SE_49mm_01.mp3'),
  'SE_Appear_01a.mp3': require('../../assets/sound/SE_Appear_01a.mp3'),
  'SE_Answer_01.mp3': require('../../assets/sound/SE_Answer_01.mp3'),
  'SE_Crow_04.wav': require('../../assets/sound/SE_Crow_04.wav'),
  'SE_BoomEffect_02.mp3': require('../../assets/sound/SE_BoomEffect_02.mp3'),
  'SE_Drill_02.mp3': require('../../assets/sound/SE_Drill_02.mp3'),
  'SE_DoorSlowOpen_01.mp3': require('../../assets/sound/SE_DoorSlowOpen_01.mp3'),
  'SE_DoorClose_01.mp3': require('../../assets/sound/SE_DoorClose_01.mp3'),
  'SE_DoorBell_01.mp3': require('../../assets/sound/SE_DoorBell_01.mp3'),
  'SE_Dog_01a.mp3': require('../../assets/sound/SE_Dog_01a.mp3'),
  'SE_Denied_01.mp3': require('../../assets/sound/SE_Denied_01.mp3'),
  'SE_Cup_02.mp3': require('../../assets/sound/SE_Cup_02.mp3'),
  'SE_Crowd_05.mp3': require('../../assets/sound/SE_Crowd_05.mp3'),
  'SE_Crowd_02.mp3': require('../../assets/sound/SE_Crowd_02.mp3'),
  'SE_Cricket_01.mp3': require('../../assets/sound/SE_Cricket_01.mp3'),
  'SE_Cook_03.mp3': require('../../assets/sound/SE_Cook_03.mp3'),
  'SE_Confirm_02.mp3': require('../../assets/sound/SE_Confirm_02.mp3'),
  'SE_Confirm_01.mp3': require('../../assets/sound/SE_Confirm_01.mp3'),
  'SE_ClockAlarm_01.mp3': require('../../assets/sound/SE_ClockAlarm_01.mp3'),
  'SE_Clock_02.mp3': require('../../assets/sound/SE_Clock_02.mp3'),
  'SE_Clap_01.mp3': require('../../assets/sound/SE_Clap_01.mp3'),
  'SE_Cat_01.mp3': require('../../assets/sound/SE_Cat_01.mp3'),
  'SE_Cartoon_02.mp3': require('../../assets/sound/SE_Cartoon_02.mp3'),
  'SE_Cartoon_01.mp3': require('../../assets/sound/SE_Cartoon_01.mp3'),
  'SE_CarHorn_01.mp3': require('../../assets/sound/SE_CarHorn_01.mp3'),
  'SE_BushRusting_02b.mp3': require('../../assets/sound/SE_BushRusting_02b.mp3'),
  'SE_Burning_02.mp3': require('../../assets/sound/SE_Burning_02.mp3'),
  'SE_Bug_01.mp3': require('../../assets/sound/SE_Bug_01.mp3'),
  'SE_BoxShake_02.mp3': require('../../assets/sound/SE_BoxShake_02.mp3'),
  'SE_BoomFuse_02a.mp3': require('../../assets/sound/SE_BoomFuse_02a.mp3'),
  'SE_Boom_01.mp3': require('../../assets/sound/SE_Boom_01.mp3'),
  'SE_Book_02.mp3': require('../../assets/sound/SE_Book_02.mp3'),
  'SE_Bird_01.mp3': require('../../assets/sound/SE_Bird_01.mp3'),
  'SE_BikeBell_01.mp3': require('../../assets/sound/SE_BikeBell_01.mp3'),
  'SE_BeepScreen_01.mp3': require('../../assets/sound/SE_BeepScreen_01.mp3'),
  'SE_Beep_01.mp3': require('../../assets/sound/SE_Beep_01.mp3'),
  'SE_Bear_01.mp3': require('../../assets/sound/SE_Bear_01.mp3'),
  'SE_Army_01.mp3': require('../../assets/sound/SE_Army_01.mp3'),
  'SE_Alarm_02.mp3': require('../../assets/sound/SE_Alarm_02.mp3'),
} as const;

/* Expression */
export const expressionMap: Record<string, any> = {
  'Headpat.png': require('../../assets/images/expression/Headpat.png'),
  'question_mark.png': require('../../assets/images/expression/question_mark.png'),
  'Question2.png': require('../../assets/images/expression/Question2.png'),
  'sweat.png': require('../../assets/images/expression/sweat.png'),
} as const;
